### ISSUE TITLE
What fork of dmenu are you running?

### ISSUE THREAD

**Issue by wtfaremyinitials** [RyanMcG/center_dmenu#3]
I don't have `-h` or `-d`

**Comment by RyanMcG** [comment]
I actually don't use this code anymore. I use my own fork of dmenu: https://github.com/RyanMcG/dmenu

I typically execute it like so:

```
dmenu_run -c -lr 2 -d 0.1 -fn 'Inconsolata for Powerline-10'
```

By putting the centering logic into dmenu I was able to get much better multi-monitor behaviour.

I will make an attempt to fix up the README to this repo and my dmenu fork.
